package org.igt.enums;

/**
 * All ENUMs used in framework
 * Mar 14, 2022
 * @author Mandeep Sheoran
 * @version 1.0
 * @since 1.0
 */
public enum PropertiesType {
	BASEURL,
	SENDRESULTSTOELK,
	DASHBOARDURL,		
	URL,
	PORTALUSERNAME,
	PORTALPASSWORD,
	OVERRIDEREPORTS,
	PASSEDSTEPSSCREENSHOT,
	FAILEDSTEPSSCREENSHOT,
	SKIPPEDSTEPSSCREENSHOT,
	FAILEDRETRYTESTS,
	RUNMODE,
	SELENIUMGRIDURL,
	ELKURL,
	BROWSER,
	LGAUNITYURL,
	NOTIFICATIONURL,
	AIRPORTDASHBOARDURL, 
	SENDRESULTSTOTESTRAIL,
	TESTRAILUSERNAME,
	TESRRAILPASSWORD,
	TESTRAILHOSTNAME,
	TESTRAILTESTRUNID	
}
